-- ==========================================
-- SmartCV AI - 20 Professional Job Offers Seed
-- Generated by Senior Supabase Database Engineer
-- ==========================================

-- 1. Create the job_offers table if not exists with correct schema
CREATE TABLE IF NOT EXISTS job_offers (
  id TEXT PRIMARY KEY,
  job_title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  location TEXT,
  industry TEXT,
  employment_type TEXT,
  experience_level TEXT,
  salary_range TEXT,
  job_description TEXT,
  required_skills JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE job_offers ENABLE ROW LEVEL SECURITY;

-- Configure RLS policies
DROP POLICY IF EXISTS "Job offers SELECT policy" ON job_offers;
CREATE POLICY "Job offers SELECT policy" ON job_offers FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Job offers INSERT/UPDATE/DELETE policy" ON job_offers;
CREATE POLICY "Job offers INSERT/UPDATE/DELETE policy" ON job_offers FOR ALL TO public
  USING (true) WITH CHECK (true);

-- Grant privileges
GRANT ALL ON TABLE job_offers TO anon, authenticated;

-- 2. Clean existing records for fresh re-seed (Ensuring Idempotency)
DELETE FROM job_offers;
DELETE FROM jobs;

-- ============================================================================
-- SECTOR 1: SOFTWARE ENGINEERING (2 jobs)
-- ============================================================================

-- Job 1: Senior Full-Stack Engineer (Senior) @ Stripe
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_01',
  'Senior Full-Stack Engineer',
  'Stripe',
  'Seattle, WA (Remote)',
  'Software Engineering',
  'Full-time',
  'Senior',
  '$160,000 - $210,000',
  'We are looking for a Senior Full-Stack Engineer to architect and build the next generation of our global merchant dashboards. In this role, you will lead the implementation of reliable web banking applications that process millions of transactions per day. You will collaborate with design, product management, and systems engineering to ensure API responsiveness, frontend performance, and fault-tolerant system integration. You will mentor junior and mid-level programmers and set engineering standard practices across the tech stack.',
  '["React", "Node.js", "TypeScript", "REST APIs", "SQL", "PostgreSQL", "AWS", "System Architecture", "Security Protocols"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_01',
  'Senior Full-Stack Engineer',
  'Stripe',
  'Seattle, WA (Remote)',
  'Software Engineering',
  'Full-time',
  'We are looking for a Senior Full-Stack Engineer to architect and build the next generation of our global merchant dashboards. In this role, you will lead the implementation of reliable web banking applications that process millions of transactions per day. You will collaborate with design, product management, and systems engineering to ensure API responsiveness, frontend performance, and fault-tolerant system integration. You will mentor junior and mid-level programmers and set engineering standard practices across the tech stack.',
  '["React", "Node.js", "TypeScript", "REST APIs", "SQL", "PostgreSQL", "AWS", "System Architecture", "Security Protocols"]'::jsonb,
  '$160,000 - $210,000',
  NOW()
);

-- Job 2: Junior Frontend Developer (Junior) @ Linear
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_02',
  'Junior Frontend Developer',
  'Linear',
  'San Francisco, CA (Hybrid)',
  'Software Engineering',
  'Full-time',
  'Junior',
  '$90,000 - $115,000',
  'Linear is searching for an ambitious Junior Frontend Developer with an eye for pixel-perfect user experiences and high performance. You will help build out fluid transitions, real-time ticket statuses, and responsive components using React and Tailwind CSS. You will work within our seasoned design and engineer taskforces to translate creative systems into beautifully active screens. Our ideal candidate is comfortable with modern React hooks, git-based workflows, and enjoys polishing details like micro-interactions and transitions.',
  '["React", "JavaScript", "TypeScript", "HTML", "CSS", "Tailwind CSS", "Git", "Responsive Design"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_02',
  'Junior Frontend Developer',
  'Linear',
  'San Francisco, CA (Hybrid)',
  'Software Engineering',
  'Full-time',
  'Linear is searching for an ambitious Junior Frontend Developer with an eye for pixel-perfect user experiences and high performance. You will help build out fluid transitions, real-time ticket statuses, and responsive components using React and Tailwind CSS. You will work within our seasoned design and engineer taskforces to translate creative systems into beautifully active screens. Our ideal candidate is comfortable with modern React hooks, git-based workflows, and enjoys polishing details like micro-interactions and transitions.',
  '["React", "JavaScript", "TypeScript", "HTML", "CSS", "Tailwind CSS", "Git", "Responsive Design"]'::jsonb,
  '$90,000 - $115,000',
  NOW()
);

-- ============================================================================
-- SECTOR 2: DATA SCIENCE (2 jobs)
-- ============================================================================

-- Job 3: Mid-Level Data Scientist (Mid-Level) @ Netflix
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_03',
  'Mid-Level Data Scientist',
  'Netflix',
  'Los Gatos, CA (Remote)',
  'Data Science',
  'Full-time',
  'Mid-Level',
  '$130,000 - $165,000',
  'Join Netflix as a Data Scientist on our content recommendation squad. You will lead the analysis of viewing habits to design custom streaming suggestions. You will develop predictive metrics, deploy experiments, and design detailed dashboard insights to help guide strategic acquisitions. In this role, you will leverage SQL, Python, and big data clusters to build datasets, run cohort analyses, and present clear diagnostic graphs to executive teams.',
  '["Python", "SQL", "Pandas", "NumPy", "A/B Testing", "Tableau", "Data Modeling", "Big Data"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_03',
  'Mid-Level Data Scientist',
  'Netflix',
  'Los Gatos, CA (Remote)',
  'Data Science',
  'Full-time',
  'Join Netflix as a Data Scientist on our content recommendation squad. You will lead the analysis of viewing habits to design custom streaming suggestions. You will develop predictive metrics, deploy experiments, and design detailed dashboard insights to help guide strategic acquisitions. In this role, you will leverage SQL, Python, and big data clusters to build datasets, run cohort analyses, and present clear diagnostic graphs to executive teams.',
  '["Python", "SQL", "Pandas", "NumPy", "A/B Testing", "Tableau", "Data Modeling", "Big Data"]'::jsonb,
  '$130,000 - $165,000',
  NOW()
);

-- Job 4: Data Science Intern (Internship) @ Airbnb
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_04',
  'Data Science Intern',
  'Airbnb',
  'San Francisco, CA (Hybrid)',
  'Data Science',
  'Internship',
  'Internship',
  '$45 - $60 / Hour',
  'We are offering a summer Data Science Internship for current students eager to apply scholastic modeling methods to real hospitality data. Supported by a senior mentor, you will clean raw event streams, run queries to analyze booking trends, and formulate statistical hypotheses. This is a highly collaborative role where you will present your conclusions to engineering teams and contribute directly to active data processing pipelines.',
  '["SQL", "Python", "R", "Data Cleaning", "Matplotlib", "Seaborn", "Excel", "Data Wrangling"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_04',
  'Data Science Intern',
  'Airbnb',
  'San Francisco, CA (Hybrid)',
  'Data Science',
  'Internship',
  'We are offering a summer Data Science Internship for current students eager to apply scholastic modeling methods to real hospitality data. Supported by a senior mentor, you will clean raw event streams, run queries to analyze booking trends, and formulate statistical hypotheses. This is a highly collaborative role where you will present your conclusions to engineering teams and contribute directly to active data processing pipelines.',
  '["SQL", "Python", "R", "Data Cleaning", "Matplotlib", "Seaborn", "Excel", "Data Wrangling"]'::jsonb,
  '$45 - $60 / Hour',
  NOW()
);

-- ============================================================================
-- SECTOR 3: ARTIFICIAL INTELLIGENCE (2 jobs)
-- ============================================================================

-- Job 5: Senior Machine Learning Engineer (Senior) @ OpenAI
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_05',
  'Senior Machine Learning Engineer',
  'OpenAI',
  'San Francisco, CA (On-site)',
  'Artificial Intelligence',
  'Full-time',
  'Senior',
  '$220,000 - $290,000',
  'OpenAI is seeking a Senior ML Engineer to scale, retrain, and optimize core neural architectures. You will deploy massive parallel model jobs, design custom evaluation loops, and build robust safety filters. You should have comfortable experience with PyTorch, distributed CUDA training, and specialized quantization. This role involves working at the cutting edge of modern neural intelligence and requires a strong background in mathematical concepts.',
  '["PyTorch", "Python", "CUDA", "TensorFlow", "Deep Learning", "LLMs", "Distributed Training", "Quantization"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_05',
  'Senior Machine Learning Engineer',
  'OpenAI',
  'San Francisco, CA (On-site)',
  'Artificial Intelligence',
  'Full-time',
  'OpenAI is seeking a Senior ML Engineer to scale, retrain, and optimize core neural architectures. You will deploy massive parallel model jobs, design custom evaluation loops, and build robust safety filters. You should have comfortable experience with PyTorch, distributed CUDA training, and specialized quantization. This role involves working at the cutting edge of modern neural intelligence and requires a strong background in mathematical concepts.',
  '["PyTorch", "Python", "CUDA", "TensorFlow", "Deep Learning", "LLMs", "Distributed Training", "Quantization"]'::jsonb,
  '$220,000 - $290,000',
  NOW()
);

-- Job 6: Mid-Level AI Product Engineer (Mid-Level) @ Anthropic
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_06',
  'Mid-Level AI Product Engineer',
  'Anthropic',
  'San Francisco, CA (Hybrid)',
  'Artificial Intelligence',
  'Full-time',
  'Mid-Level',
  '$145,000 - $185,000',
  'We are seeking a Mid-Level AI Product Engineer to design safe, responsive interface pipelines that connect LLMs to consumer applications. You will draft detailed prompt scripts, structure conversational contextual buffers, and implement caching systems to reduce inference latency. You will collaborate on both server-side logic and client interfaces to construct features like semantic searching, smart summary blocks, and interactive AI helpers.',
  '["Python", "TypeScript", "Node.js", "LLM APIs", "LangChain", "Vector Databases", "Prompt Engineering", "Vite"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_06',
  'Mid-Level AI Product Engineer',
  'Anthropic',
  'San Francisco, CA (Hybrid)',
  'Artificial Intelligence',
  'Full-time',
  'We are seeking a Mid-Level AI Product Engineer to design safe, responsive interface pipelines that connect LLMs to consumer applications. You will draft detailed prompt scripts, structure conversational contextual buffers, and implement caching systems to reduce inference latency. You will collaborate on both server-side logic and client interfaces to construct features like semantic searching, smart summary blocks, and interactive AI helpers.',
  '["Python", "TypeScript", "Node.js", "LLM APIs", "LangChain", "Vector Databases", "Prompt Engineering", "Vite"]'::jsonb,
  '$145,000 - $185,000',
  NOW()
);

-- ============================================================================
-- SECTOR 4: CYBERSECURITY (2 jobs)
-- ============================================================================

-- Job 7: Senior Security Analyst (Senior) @ CrowdStrike
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_07',
  'Senior Security Analyst',
  'CrowdStrike',
  'Austin, TX (Remote)',
  'Cybersecurity',
  'Full-time',
  'Senior',
  '$140,000 - $180,000',
  'CrowdStrike is search of a Senior Security Analyst to lead critical incident response tasks and threat-hunting workflows. You will inspect alerts, reconstruct security events across endpoints, and design custom rules to stop attack vectors. In this role, you will perform memory analysis, analyze suspicious payloads, and write comprehensive advisory write-ups for executive protection squads worldwide.',
  '["SIEM", "Incident Response", "Network Security", "Penetration Testing", "Wireshark", "IDS/IPS", "Scripting", "Threat Hunting"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_07',
  'Senior Security Analyst',
  'CrowdStrike',
  'Austin, TX (Remote)',
  'Cybersecurity',
  'Full-time',
  'CrowdStrike is search of a Senior Security Analyst to lead critical incident response tasks and threat-hunting workflows. You will inspect alerts, reconstruct security events across endpoints, and design custom rules to stop attack vectors. In this role, you will perform memory analysis, analyze suspicious payloads, and write comprehensive advisory write-ups for executive protection squads worldwide.',
  '["SIEM", "Incident Response", "Network Security", "Penetration Testing", "Wireshark", "IDS/IPS", "Scripting", "Threat Hunting"]'::jsonb,
  '$140,000 - $180,000',
  NOW()
);

-- Job 8: Junior Security Engineer (Junior) @ Cloudflare
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_08',
  'Junior Security Engineer',
  'Cloudflare',
  'San Francisco, CA (Hybrid)',
  'Cybersecurity',
  'Full-time',
  'Junior',
  '$85,000 - $110,000',
  'Cloudflare is hiring a Junior Security Engineer to audit and secure internal systems. You will assist in executing vulnerability Scans, reviewing firewall filters, and monitoring network access logs. You will collaborate on security training, verify dependency updates, and research emergent cyber threats. This role is a perfect start for an engineer who desires deep exposure to firewalls, SSL/TLS, and modern identity principles.',
  '["Network Security", "Linux", "SSL/TLS", "Vulnerability Scanning", "Nmap", "Firewalls", "Python", "Git"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_08',
  'Junior Security Engineer',
  'Cloudflare',
  'San Francisco, CA (Hybrid)',
  'Cybersecurity',
  'Full-time',
  'Cloudflare is hiring a Junior Security Engineer to audit and secure internal systems. You will assist in executing vulnerability Scans, reviewing firewall filters, and monitoring network access logs. You will collaborate on security training, verify dependency updates, and research emergent cyber threats. This role is a perfect start for an engineer who desires deep exposure to firewalls, SSL/TLS, and modern identity principles.',
  '["Network Security", "Linux", "SSL/TLS", "Vulnerability Scanning", "Nmap", "Firewalls", "Python", "Git"]'::jsonb,
  '$85,000 - $110,000',
  NOW()
);

-- ============================================================================
-- SECTOR 5: MARKETING (2 jobs)
-- ============================================================================

-- Job 9: Mid-Level Growth Marketing Manager (Mid-Level) @ Notion
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_09',
  'Mid-Level Growth Marketing Manager',
  'Notion',
  'New York, NY (Remote)',
  'Marketing',
  'Full-time',
  'Mid-Level',
  '$110,000 - $135,000',
  'Notion is looking for a multi-faceted Growth Marketing Manager to oversee paid acquisitions, SEO content strategies, and email campaigns. You will coordinate with our design crew to create conversion assets and run A/B optimizations to drive signups. Essential expectations include handling major analytics boards (Google Analytics), running search campaigns, and drafting crisp narratives that appeal to developers.',
  '["SEO", "Google Analytics", "SEM", "Copywriting", "A/B Testing", "Email Marketing", "SQL", "Social Media Marketing"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_09',
  'Mid-Level Growth Marketing Manager',
  'Notion',
  'New York, NY (Remote)',
  'Marketing',
  'Full-time',
  'Notion is looking for a multi-faceted Growth Marketing Manager to oversee paid acquisitions, SEO content strategies, and email campaigns. You will coordinate with our design crew to create conversion assets and run A/B optimizations to drive signups. Essential expectations include handling major analytics boards (Google Analytics), running search campaigns, and drafting crisp narratives that appeal to developers.',
  '["SEO", "Google Analytics", "SEM", "Copywriting", "A/B Testing", "Email Marketing", "SQL", "Social Media Marketing"]'::jsonb,
  '$110,000 - $135,000',
  NOW()
);

-- Job 10: Marketing Intern (Internship) @ Figma
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_10',
  'Marketing Intern',
  'Figma',
  'Paris, France (Hybrid)',
  'Marketing',
  'Internship',
  'Internship',
  '€30,000 - €38,000 / Year',
  'Join Figma as a Marketing Intern on our European Community team. You will support online workshops, gather creator reviews, organize social calendars, and track engagement across community portals. Candidates should have a creative mindset, excellent written communication, familiarity with social channels, and basic experience using design software to build posts.',
  '["Social Media Management", "Content Creation", "Figma", "Market Research", "Events Coordination", "Copywriting", "French"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_10',
  'Marketing Intern',
  'Figma',
  'Paris, France (Hybrid)',
  'Marketing',
  'Internship',
  'Join Figma as a Marketing Intern on our European Community team. You will support online workshops, gather creator reviews, organize social calendars, and track engagement across community portals. Candidates should have a creative mindset, excellent written communication, familiarity with social channels, and basic experience using design software to build posts.',
  '["Social Media Management", "Content Creation", "Figma", "Market Research", "Events Coordination", "Copywriting", "French"]'::jsonb,
  '€30,000 - €38,000 / Year',
  NOW()
);

-- ============================================================================
-- SECTOR 6: HUMAN RESOURCES (2 jobs)
-- ============================================================================

-- Job 11: Senior HR Business Partner (Senior) @ Deel
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_11',
  'Senior HR Business Partner',
  'Deel',
  'London, UK (Remote)',
  'Human Resources',
  'Full-time',
  'Senior',
  '£110,000 - £140,000',
  'Deel is searching for a Senior HR Business Partner to support our global engineering and Operations squads. You will align human resource frameworks with broader organizational objectives, oversee compensation and workforce reviews, and resolve complex employee relations cases. Extensive knowledge of UK labor compliance, performance management systems, and organizational design standards is required.',
  '["Employee Relations", "UK Labor Law", "Performance Management", "Workforce Planning", "Conflict Resolution", "HRIS", "Compensation Strategy"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_11',
  'Senior HR Business Partner',
  'Deel',
  'London, UK (Remote)',
  'Human Resources',
  'Full-time',
  'Deel is searching for a Senior HR Business Partner to support our global engineering and Operations squads. You will align human resource frameworks with broader organizational objectives, oversee compensation and workforce reviews, and resolve complex employee relations cases. Extensive knowledge of UK labor compliance, performance management systems, and organizational design standards is required.',
  '["Employee Relations", "UK Labor Law", "Performance Management", "Workforce Planning", "Conflict Resolution", "HRIS", "Compensation Strategy"]'::jsonb,
  '£110,000 - £140,000',
  NOW()
);

-- Job 12: Junior Talent Acquisition Coordinator (Junior) @ Retool
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_12',
  'Junior Talent Acquisition Coordinator',
  'Retool',
  'San Francisco, CA (On-site)',
  'Human Resources',
  'Full-time',
  'Junior',
  '$75,000 - $95,000',
  'Retool is growing and we are seeking an dynamic Talent Coordinator to manage candidate tracking and schedule interviews across technical panels. You will handle workflows in our ATS (Ashby), coordinate complex multi-timezone panels, draft invitation templates, and ensure every candidate leaves with an extraordinary impression of our culture. You will also help run university hiring initiatives.',
  '["Candidate Management", "Applicant Tracking Systems", "Ashby", "Google Calendar", "Scheduling", "Written Communication", "Detail Oriented"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_12',
  'Junior Talent Acquisition Coordinator',
  'Retool',
  'San Francisco, CA (On-site)',
  'Human Resources',
  'Full-time',
  'Retool is growing and we are seeking an dynamic Talent Coordinator to manage candidate tracking and schedule interviews across technical panels. You will handle workflows in our ATS (Ashby), coordinate complex multi-timezone panels, draft invitation templates, and ensure every candidate leaves with an extraordinary impression of our culture. You will also help run university hiring initiatives.',
  '["Candidate Management", "Applicant Tracking Systems", "Ashby", "Google Calendar", "Scheduling", "Written Communication", "Detail Oriented"]'::jsonb,
  '$75,000 - $95,000',
  NOW()
);

-- ============================================================================
-- SECTOR 7: ACCOUNTING (2 jobs)
-- ============================================================================

-- Job 13: Mid-Level Corporate Accountant (Mid-Level) @ Carta
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_13',
  'Mid-Level Corporate Accountant',
  'Carta',
  'New York, NY (Hybrid)',
  'Accounting',
  'Full-time',
  'Mid-Level',
  '$105,000 - $130,000',
  'Carta is hunting for a corporate Accountant to execute our monthly ledger closing tasks, reconcile active balance listings, and coordinate seasonal corporate tax filings. You will analyze amortization tables and make sure that all policies perfectly reflect US GAAP framework compliance. Ideal profiles possess solid experience with ERP software (NetSuite), premium Excel skill indexes, and a deep appreciation for spreadsheet details.',
  '["US GAAP", "General Ledger", "NetSuite", "Excel Macros", "Account Reconciliation", "Fixed Assets", "Corporate Tax"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_13',
  'Mid-Level Corporate Accountant',
  'Carta',
  'New York, NY (Hybrid)',
  'Accounting',
  'Full-time',
  'Carta is hunting for a corporate Accountant to execute our monthly ledger closing tasks, reconcile active balance listings, and coordinate seasonal corporate tax filings. You will analyze amortization tables and make sure that all policies perfectly reflect US GAAP framework compliance. Ideal profiles possess solid experience with ERP software (NetSuite), premium Excel skill indexes, and a deep appreciation for spreadsheet details.',
  '["US GAAP", "General Ledger", "NetSuite", "Excel Macros", "Account Reconciliation", "Fixed Assets", "Corporate Tax"]'::jsonb,
  '$105,000 - $130,000',
  NOW()
);

-- Job 14: Accounting Intern (Internship) @ Brex
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_14',
  'Accounting Intern',
  'Brex',
  'Remote (US)',
  'Accounting',
  'Internship',
  'Internship',
  '$30 - $45 / Hour',
  'Join Brex as a virtual Accounting Intern. In this role, you will help our finance squad categorize corporate card transactions, organize digital invoice receipts, and cross-reference bank entries. You will pick up real-world workflows in modern accounting suites, learn internal billing controls, and build clean reports. High proficiency in quantitative assessments is required.',
  '["Excel", "Account Categorization", "Invoice Auditing", "Bookkeeping", "Data Entry", "Detail Oriented", "Finance Reporting"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_14',
  'Accounting Intern',
  'Brex',
  'Remote (US)',
  'Accounting',
  'Internship',
  'Join Brex as a virtual Accounting Intern. In this role, you will help our finance squad categorize corporate card transactions, organize digital invoice receipts, and cross-reference bank entries. You will pick up real-world workflows in modern accounting suites, learn internal billing controls, and build clean reports. High proficiency in quantitative assessments is required.',
  '["Excel", "Account Categorization", "Invoice Auditing", "Bookkeeping", "Data Entry", "Detail Oriented", "Finance Reporting"]'::jsonb,
  '$30 - $45 / Hour',
  NOW()
);

-- ============================================================================
-- SECTOR 8: FINANCE (2 jobs)
-- ============================================================================

-- Job 15: Senior Financial Analyst (Senior) @ Ramp
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_15',
  'Senior Financial Analyst',
  'Ramp',
  'New York, NY (On-site)',
  'Finance',
  'Full-time',
  'Senior',
  '$150,000 - $190,000',
  'Ramp is looking for a Senior Financial Analyst to design robust FP&A forecasts, construct unit economics trackers, and formulate long-term capital allocation projections. You will construct complex financial sheets, track variance budgets across global taskforces, and prepare comprehensive summary reports for our board of directors. Strong SQL credentials and financial modeling expertise are required.',
  '["FP&A", "Financial Modeling", "Corporate Finance", "SQL", "Excel Models", "Budget Forecasting", "KPI Dashboards"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_15',
  'Senior Financial Analyst',
  'Ramp',
  'New York, NY (On-site)',
  'Finance',
  'Full-time',
  'Ramp is looking for a Senior Financial Analyst to design robust FP&A forecasts, construct unit economics trackers, and formulate long-term capital allocation projections. You will construct complex financial sheets, track variance budgets across global taskforces, and prepare comprehensive summary reports for our board of directors. Strong SQL credentials and financial modeling expertise are required.',
  '["FP&A", "Financial Modeling", "Corporate Finance", "SQL", "Excel Models", "Budget Forecasting", "KPI Dashboards"]'::jsonb,
  '$150,000 - $190,000',
  NOW()
);

-- Job 16: Junior Investment Analyst (Junior) @ Robinhood
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_16',
  'Junior Investment Analyst',
  'Robinhood',
  'Menlo Park, CA (Hybrid)',
  'Finance',
  'Full-time',
  'Junior',
  '$85,000 - $105,000',
  'Join our brokerage operations as a Junior Investment Analyst. You will collect capital market metrics, write concise briefing reports on corporate filings, and track portfolio asset allocations. You will help extract data from SEC papers, update pricing feeds, and evaluate equity metrics. Candidates should possess strong analytical minds, clean report-writing skills, and an active interest in financial markets.',
  '["Financial Analysis", "Market Research", "SEC Filings", "Excel", "Data Visualization", "Equity Research", "Python"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_16',
  'Junior Investment Analyst',
  'Robinhood',
  'Menlo Park, CA (Hybrid)',
  'Finance',
  'Full-time',
  'Join our brokerage operations as a Junior Investment Analyst. You will collect capital market metrics, write concise briefing reports on corporate filings, and track portfolio asset allocations. You will help extract data from SEC papers, update pricing feeds, and evaluate equity metrics. Candidates should possess strong analytical minds, clean report-writing skills, and an active interest in financial markets.',
  '["Financial Analysis", "Market Research", "SEC Filings", "Excel", "Data Visualization", "Equity Research", "Python"]'::jsonb,
  '$85,000 - $105,000',
  NOW()
);

-- ============================================================================
-- SECTOR 9: PROJECT MANAGEMENT (2 jobs)
-- ============================================================================

-- Job 17: Mid-Level Technical Project Manager (Mid-Level) @ Asana
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_17',
  'Technical Project Manager',
  'Asana',
  'San Francisco, CA (Remote)',
  'Project Management',
  'Full-time',
  'Mid-Level',
  '$120,000 - $145,000',
  'Asana is looking for a technical Agile Project Manager to align our product roadmap deliverables with active engineering milestones. You will manage daily standups, clear project blockers, compile comprehensive sprint metrics, and streamline multi-team schedules. Essential qualifications include robust understanding of Scrum and Agile principles, experience with CI/CD delivery models, and excellent communication habits.',
  '["Scrum", "Agile Methodologies", "Sprint Planning", "Jira", "Risk Management", "Asana Platform", "SDLC", "CI/CD Concepts"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_17',
  'Technical Project Manager',
  'Asana',
  'San Francisco, CA (Remote)',
  'Project Management',
  'Full-time',
  'Asana is looking for a technical Agile Project Manager to align our product roadmap deliverables with active engineering milestones. You will manage daily standups, clear project blockers, compile comprehensive sprint metrics, and streamline multi-team schedules. Essential qualifications include robust understanding of Scrum and Agile principles, experience with CI/CD delivery models, and excellent communication habits.',
  '["Scrum", "Agile Methodologies", "Sprint Planning", "Jira", "Risk Management", "Asana Platform", "SDLC", "CI/CD Concepts"]'::jsonb,
  '$120,000 - $145,000',
  NOW()
);

-- Job 18: Project Management Intern (Internship) @ Miro
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_18',
  'Project Management Intern',
  'Miro',
  'Amsterdam, Netherlands (Remote)',
  'Project Management',
  'Internship',
  'Internship',
  '€2,000 - €2,800 / Month',
  'We are offering a remote Project Management Internship for digital coordinators. You will help schedule program reviews, document technical requirement papers, track status boards, and draft team updates. This role is a prime opportunity to master digital workspace patterns, learn agile sprint processes, and manage cross-timezone schedules inside a major SaaS enterprise.',
  '["Agile Processes", "Confluence", "Miro Boards", "Documentation", "Project Coordination", "Time Management", "Collaboration"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_18',
  'Project Management Intern',
  'Miro',
  'Amsterdam, Netherlands (Remote)',
  'Project Management',
  'Internship',
  'We are offering a remote Project Management Internship for digital coordinators. You will help schedule program reviews, document technical requirement papers, track status boards, and draft team updates. This role is a prime opportunity to master digital workspace patterns, learn agile sprint processes, and manage cross-timezone schedules inside a major SaaS enterprise.',
  '["Agile Processes", "Confluence", "Miro Boards", "Documentation", "Project Coordination", "Time Management", "Collaboration"]'::jsonb,
  '€2,000 - €2,800 / Month',
  NOW()
);

-- ============================================================================
-- SECTOR 10: BUSINESS ANALYSIS (2 jobs)
-- ============================================================================

-- Job 19: Senior Operations Business Analyst (Senior) @ Uber
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_19',
  'Senior Operations Business Analyst',
  'Uber',
  'San Francisco, CA (On-site)',
  'Business Analysis',
  'Full-time',
  'Senior',
  '$145,000 - $185,000',
  'Uber is hiring a Senior Business Analyst to optimize supply-demand pricing strategies. You will inspect millions of trip records, build live Tableau metrics, and identify marketplace friction factors. Strong technical proficiency in SQL and Python is required, as well as a track record of applying statistical models (e.g., linear regressions) to refine logistical outcomes.',
  '["SQL", "Python", "Tableau", "Business Analytics", "Statistical Modeling", "Dashboard Design", "Excel Macros", "Requirements Gathering"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_19',
  'Senior Operations Business Analyst',
  'Uber',
  'San Francisco, CA (On-site)',
  'Business Analysis',
  'Full-time',
  'Uber is hiring a Senior Business Analyst to optimize supply-demand pricing strategies. You will inspect millions of trip records, build live Tableau metrics, and identify marketplace friction factors. Strong technical proficiency in SQL and Python is required, as well as a track record of applying statistical models (e.g., linear regressions) to refine logistical outcomes.',
  '["SQL", "Python", "Tableau", "Business Analytics", "Statistical Modeling", "Dashboard Design", "Excel Macros", "Requirements Gathering"]'::jsonb,
  '$145,000 - $185,000',
  NOW()
);

-- Job 20: Junior Business Systems Analyst (Junior) @ Slack
INSERT INTO job_offers (id, job_title, company_name, location, industry, employment_type, experience_level, salary_range, job_description, required_skills, created_at)
VALUES (
  'job_off_20',
  'Junior Business Systems Analyst',
  'Slack',
  'Denver, CO (Remote)',
  'Business Analysis',
  'Full-time',
  'Junior',
  '$80,000 - $100,000',
  'Join Slack as a Junior Business Systems Analyst on our internal tooling taskforce. You will analyze internal workflows, write specifications, and configure enterprise solutions (Salesforce). You will gather stakeholder requirements, map data integrations, and build training tutorials. This is a brilliant launching pad for business professionals who want to bridge corporate operations with advanced software designs.',
  '["Business Analysis", "Requirements Gathering", "UML Diagrams", "Salesforce CRM", "Jira", "Technical Writing", "SQL", "Google Sheets"]'::jsonb,
  NOW()
);

INSERT INTO jobs (id, title, company, location, category, type, description, requirements, salary, "postedAt")
VALUES (
  'job_off_20',
  'Junior Business Systems Analyst',
  'Slack',
  'Denver, CO (Remote)',
  'Business Analysis',
  'Full-time',
  'Join Slack as a Junior Business Systems Analyst on our internal tooling taskforce. You will analyze internal workflows, write specifications, and configure enterprise solutions (Salesforce). You will gather stakeholder requirements, map data integrations, and build training tutorials. This is a brilliant launching pad for business professionals who want to bridge corporate operations with advanced software designs.',
  '["Business Analysis", "Requirements Gathering", "UML Diagrams", "Salesforce CRM", "Jira", "Technical Writing", "SQL", "Google Sheets"]'::jsonb,
  '$80,000 - $100,000',
  NOW()
);
