-- ==========================================
-- SmartCV AI Complete Database Schema & RLS Audit
-- Generated by Senior Supabase Database Architect
-- ==========================================

-- --------------------------------------------------
-- 1. Table Definitions
-- --------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  "passwordHash" TEXT NOT NULL,
  name TEXT NOT NULL,
  "tenantId" TEXT NOT NULL,
  title TEXT,
  bio TEXT,
  language TEXT DEFAULT 'fr',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cvs (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  "fileName" TEXT NOT NULL,
  status TEXT,
  score INTEGER,
  "grammarScore" INTEGER,
  "impactScore" INTEGER,
  "skillsScore" INTEGER,
  summary TEXT,
  suggestions JSONB,
  strengths JSONB,
  weaknesses JSONB,
  "atsOptimizations" JSONB,
  "grammarImprovements" JSONB,
  recommendations JSONB,
  "skillsMatched" JSONB,
  "skillsMissing" JSONB,
  "parsedDetails" JSONB,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analyses (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cover_letters (
  id TEXT PRIMARY KEY,
  "cvId" TEXT REFERENCES cvs(id),
  "userId" TEXT NOT NULL REFERENCES users(id),
  "recipientName" TEXT,
  "companyName" TEXT NOT NULL,
  "jobTitle" TEXT NOT NULL,
  "jobDescription" TEXT,
  "generatedText" TEXT,
  status TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT,
  category TEXT,
  type TEXT,
  description TEXT,
  requirements JSONB,
  salary TEXT,
  "postedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS job_offers (
  id TEXT PRIMARY KEY,
  job_title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  location TEXT,
  industry TEXT,
  employment_type TEXT,
  experience_level TEXT,
  salary_range TEXT,
  job_description TEXT,
  required_skills JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS matches (
  id TEXT PRIMARY KEY,
  "cvId" TEXT NOT NULL REFERENCES cvs(id),
  "jobId" TEXT NOT NULL,
  "customJob" JSONB,
  "matchScore" INTEGER,
  "fitSummary" TEXT,
  strengths JSONB,
  gaps JSONB,
  "applicationStrategy" TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS job_matches (
  id TEXT PRIMARY KEY,
  "cvId" TEXT REFERENCES cvs(id),
  "userId" TEXT REFERENCES users(id),
  "matchScore" INTEGER,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS activities (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  "tenantId" TEXT,
  type TEXT,
  message TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS interview_questions (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  "cvId" TEXT NOT NULL REFERENCES cvs(id),
  category TEXT NOT NULL,
  questions JSONB NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS career_advice (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES users(id),
  "cvId" TEXT NOT NULL REFERENCES cvs(id),
  career_paths JSONB NOT NULL,
  salary_estimation JSONB NOT NULL,
  skills_gap JSONB NOT NULL,
  roadmap JSONB NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --------------------------------------------------
-- 2. Enable Row-Level Security (RLS) on All Tables
-- --------------------------------------------------

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE cover_letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE interview_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE career_advice ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------
-- 3. Define Row-Level Security Policies
-- --------------------------------------------------

-- --- users RLS Policies ---
DROP POLICY IF EXISTS "Users SELECT policy" ON users;
CREATE POLICY "Users SELECT policy" ON users FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND id = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Users INSERT policy" ON users;
CREATE POLICY "Users INSERT policy" ON users FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND id = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Users UPDATE policy" ON users;
CREATE POLICY "Users UPDATE policy" ON users FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND id = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND id = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Users DELETE policy" ON users;
CREATE POLICY "Users DELETE policy" ON users FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND id = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- cvs RLS Policies ---
DROP POLICY IF EXISTS "Cvs SELECT policy" ON cvs;
CREATE POLICY "Cvs SELECT policy" ON cvs FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cvs INSERT policy" ON cvs;
CREATE POLICY "Cvs INSERT policy" ON cvs FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cvs UPDATE policy" ON cvs;
CREATE POLICY "Cvs UPDATE policy" ON cvs FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cvs DELETE policy" ON cvs;
CREATE POLICY "Cvs DELETE policy" ON cvs FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- analyses RLS Policies ---
DROP POLICY IF EXISTS "Analyses SELECT policy" ON analyses;
CREATE POLICY "Analyses SELECT policy" ON analyses FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Analyses INSERT policy" ON analyses;
CREATE POLICY "Analyses INSERT policy" ON analyses FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Analyses UPDATE policy" ON analyses;
CREATE POLICY "Analyses UPDATE policy" ON analyses FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Analyses DELETE policy" ON analyses;
CREATE POLICY "Analyses DELETE policy" ON analyses FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- cover_letters RLS Policies ---
DROP POLICY IF EXISTS "Cover letters SELECT policy" ON cover_letters;
CREATE POLICY "Cover letters SELECT policy" ON cover_letters FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cover letters INSERT policy" ON cover_letters;
CREATE POLICY "Cover letters INSERT policy" ON cover_letters FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cover letters UPDATE policy" ON cover_letters;
CREATE POLICY "Cover letters UPDATE policy" ON cover_letters FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Cover letters DELETE policy" ON cover_letters;
CREATE POLICY "Cover letters DELETE policy" ON cover_letters FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- jobs RLS Policies ---
DROP POLICY IF EXISTS "Jobs SELECT policy" ON jobs;
CREATE POLICY "Jobs SELECT policy" ON jobs FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Jobs INSERT/UPDATE/DELETE policy" ON jobs;
CREATE POLICY "Jobs INSERT/UPDATE/DELETE policy" ON jobs FOR ALL TO public
  USING ( (auth.role() = 'authenticated') OR (auth.role() = 'anon') );


-- --- job_offers RLS Policies ---
DROP POLICY IF EXISTS "Job offers SELECT policy" ON job_offers;
CREATE POLICY "Job offers SELECT policy" ON job_offers FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Job offers INSERT/UPDATE/DELETE policy" ON job_offers;
CREATE POLICY "Job offers INSERT/UPDATE/DELETE policy" ON job_offers FOR ALL TO public
  USING ( (auth.role() = 'authenticated') OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated') OR (auth.role() = 'anon') );


-- --- matches RLS Policies ---
DROP POLICY IF EXISTS "Matches SELECT policy" ON matches;
CREATE POLICY "Matches SELECT policy" ON matches FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "cvId" IN (SELECT id FROM cvs WHERE "userId" = auth.uid()::text)) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Matches INSERT policy" ON matches;
CREATE POLICY "Matches INSERT policy" ON matches FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "cvId" IN (SELECT id FROM cvs WHERE "userId" = auth.uid()::text)) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Matches UPDATE policy" ON matches;
CREATE POLICY "Matches UPDATE policy" ON matches FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "cvId" IN (SELECT id FROM cvs WHERE "userId" = auth.uid()::text)) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "cvId" IN (SELECT id FROM cvs WHERE "userId" = auth.uid()::text)) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Matches DELETE policy" ON matches;
CREATE POLICY "Matches DELETE policy" ON matches FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "cvId" IN (SELECT id FROM cvs WHERE "userId" = auth.uid()::text)) OR (auth.role() = 'anon') );


-- --- job_matches RLS Policies ---
DROP POLICY IF EXISTS "Job matches SELECT policy" ON job_matches;
CREATE POLICY "Job matches SELECT policy" ON job_matches FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Job matches INSERT policy" ON job_matches;
CREATE POLICY "Job matches INSERT policy" ON job_matches FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Job matches UPDATE policy" ON job_matches;
CREATE POLICY "Job matches UPDATE policy" ON job_matches FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Job matches DELETE policy" ON job_matches;
CREATE POLICY "Job matches DELETE policy" ON job_matches FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- activities RLS Policies ---
DROP POLICY IF EXISTS "Activities SELECT policy" ON activities;
CREATE POLICY "Activities SELECT policy" ON activities FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Activities INSERT policy" ON activities;
CREATE POLICY "Activities INSERT policy" ON activities FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Activities UPDATE policy" ON activities;
CREATE POLICY "Activities UPDATE policy" ON activities FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Activities DELETE policy" ON activities;
CREATE POLICY "Activities DELETE policy" ON activities FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- interview_questions RLS Policies ---
DROP POLICY IF EXISTS "Interview questions SELECT policy" ON interview_questions;
CREATE POLICY "Interview questions SELECT policy" ON interview_questions FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Interview questions INSERT policy" ON interview_questions;
CREATE POLICY "Interview questions INSERT policy" ON interview_questions FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Interview questions UPDATE policy" ON interview_questions;
CREATE POLICY "Interview questions UPDATE policy" ON interview_questions FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Interview questions DELETE policy" ON interview_questions;
CREATE POLICY "Interview questions DELETE policy" ON interview_questions FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --- career_advice RLS Policies ---
DROP POLICY IF EXISTS "Career advice SELECT policy" ON career_advice;
CREATE POLICY "Career advice SELECT policy" ON career_advice FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Career advice INSERT policy" ON career_advice;
CREATE POLICY "Career advice INSERT policy" ON career_advice FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Career advice UPDATE policy" ON career_advice;
CREATE POLICY "Career advice UPDATE policy" ON career_advice FOR UPDATE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') )
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "Career advice DELETE policy" ON career_advice;
CREATE POLICY "Career advice DELETE policy" ON career_advice FOR DELETE TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );


-- --------------------------------------------------
-- 4. Set Permissions
-- --------------------------------------------------
GRANT ALL ON TABLE users TO anon, authenticated;
GRANT ALL ON TABLE cvs TO anon, authenticated;
GRANT ALL ON TABLE analyses TO anon, authenticated;
GRANT ALL ON TABLE cover_letters TO anon, authenticated;
GRANT ALL ON TABLE jobs TO anon, authenticated;
GRANT ALL ON TABLE job_offers TO anon, authenticated;
GRANT ALL ON TABLE matches TO anon, authenticated;
GRANT ALL ON TABLE job_matches TO anon, authenticated;
GRANT ALL ON TABLE activities TO anon, authenticated;
GRANT ALL ON TABLE interview_questions TO anon, authenticated;
-- --- cv_versions Table ---
CREATE TABLE IF NOT EXISTS cv_versions (
  id TEXT PRIMARY KEY,
  "cvId" TEXT NOT NULL REFERENCES cvs(id),
  "userId" TEXT NOT NULL REFERENCES users(id),
  "versionNumber" INTEGER NOT NULL,
  "cvContent" JSONB NOT NULL,
  "atsScore" INTEGER,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE cv_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "CV versions SELECT policy" ON cv_versions;
CREATE POLICY "CV versions SELECT policy" ON cv_versions FOR SELECT TO public
  USING ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

DROP POLICY IF EXISTS "CV versions INSERT policy" ON cv_versions;
CREATE POLICY "CV versions INSERT policy" ON cv_versions FOR INSERT TO public
  WITH CHECK ( (auth.role() = 'authenticated' AND "userId" = auth.uid()::text) OR (auth.role() = 'anon') );

GRANT ALL ON TABLE cv_versions TO anon, authenticated;
