import React, { useState, useEffect } from "react";
import { PenTool, Download, FileText, CheckCircle, Copy, RefreshCcw } from "lucide-react";
import jsPDF from "jspdf";
import CoverLetterGenerator from "../CoverLetterGenerator";

export default function CoverLetters({ token }: { token: string }) {
  const [cvs, setCvs] = useState<any[]>([]);
  const [letters, setLetters] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const [form, setForm] = useState({
    cvId: "",
    jobTitle: "",
    companyName: "",
    recipientName: "",
    jobDescription: "",
    experienceLevel: "",
    skills: ""
  });

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [cvReq, lettersReq] = await Promise.all([
          fetch("/api/cvs", { headers: { "Authorization": `Bearer ${token}` } }),
          fetch("/api/cover-letters", { headers: { "Authorization": `Bearer ${token}` } })
        ]);
        
        if (!cvReq.ok || !lettersReq.ok) throw new Error("Failed to load requisite data");
        
        const cvData = await cvReq.json();
        const lettersData = await lettersReq.json();
        
        setCvs(cvData);
        setLetters(lettersData.sort((a: any, b: any) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));
        if (cvData.length > 0) {
          setForm(prev => ({ ...prev, cvId: cvData[0].id }));
        }
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [token]);

  const handleGenerate = async (e?: React.FormEvent, letterToRegenerate?: any) => {
    if (e) e.preventDefault();
    
    const targetData = letterToRegenerate || form;
    
    if (!targetData.jobTitle || !targetData.companyName) {
      setError("Please fill in the required fields (Job Title, Company).");
      return;
    }
    
    setGenerating(true);
    setError("");

    try {
      const res = await fetch("/api/cover-letters/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        },
        body: JSON.stringify({
          ...targetData,
          cvId: targetData.cvId === "none" ? "" : targetData.cvId
        })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      
      setLetters(prev => [data, ...prev]);
      if (!letterToRegenerate) {
        setForm({ ...form, jobTitle: "", companyName: "", recipientName: "", jobDescription: "", experienceLevel: "", skills: "" });
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = (letterId: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(letterId);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDownloadPDF = (letter: any) => {
    const doc = new jsPDF();
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const textAreaWidth = pageWidth - margin * 2;

    // Header styling
    doc.setFillColor(30, 41, 59); // slate-800
    doc.rect(0, 0, pageWidth, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("Cover Letter", margin, 25);
    
    // Sub-header details
    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(`Role: ${letter.jobTitle}`, margin, 55);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Company: ${letter.companyName}`, margin, 63);
    doc.text(`Date: ${new Date(letter.createdAt).toLocaleDateString()}`, margin, 71);
    
    // Line separator
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(margin, 78, pageWidth - margin, 78);

    // Letter Content
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    const splitText = doc.splitTextToSize(String(letter.generatedText || ""), textAreaWidth);
    let currentY = 90;
    
    // Simple pagination handling if cover letter is too long
    for (let i = 0; i < splitText.length; i++) {
      if (currentY > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        currentY = margin;
      }
      doc.text(splitText[i], margin, currentY);
      currentY += 6;
    }
    
    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Generated by AI CV Coach • ${new Date().getFullYear()}`, margin, pageHeight - 15);

    doc.save(`${letter.companyName.replace(/\\s+/g, '_')}_Cover_Letter.pdf`);
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="h-8 w-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div>
        <h1 className="font-display text-4xl font-bold text-white tracking-tight">AI Cover Letter Generator</h1>
        <p className="text-slate-400 mt-1">Let Gemini AI draft personalized, professional cover letters tailored to the job.</p>
      </div>

      {error && (
        <div className="bg-rose-500/10 border border-rose-500/20 text-rose-400 p-4 rounded-xl">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1 space-y-6">
          <CoverLetterGenerator token={token} cvs={cvs} onGenerated={(letter) => setLetters(prev => [letter, ...prev])} />
        </div>

        <div className="lg:col-span-2 space-y-6">
          <h3 className="text-lg font-bold text-white mb-4">Your Generated Letters</h3>
          
          {letters.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed border-slate-800 rounded-2xl bg-slate-900/30 text-center">
              <FileText className="h-10 w-10 text-slate-600 mb-3" />
              <p className="text-slate-400">No letters generated yet.</p>
            </div>
          ) : (
            <div className="space-y-6">
              {letters.map((letter) => (
                <div key={letter.id} className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm shadow-xl flex flex-col gap-4 group">
                  <div className="flex justify-between items-start border-b border-slate-800 pb-4">
                    <div>
                      <h4 className="text-lg font-bold text-white">{letter.jobTitle}</h4>
                      <p className="text-indigo-400 text-sm font-medium">@ {letter.companyName}</p>
                    </div>
                    <span className="text-xs text-slate-500 font-mono bg-slate-950 px-2 py-1 rounded border border-slate-800">
                      {new Date(letter.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                  
                  <div className="text-slate-300 text-sm leading-relaxed whitespace-pre-wrap max-h-60 overflow-y-auto pr-2 custom-scrollbar">
                    {letter.generatedText}
                  </div>
                  
                  <div className="flex flex-wrap gap-3 pt-4 border-t border-slate-800 items-center justify-between">
                    <span className="flex items-center gap-1.5 text-xs text-emerald-400">
                      <CheckCircle className="h-4 w-4" /> Ready to send
                    </span>
                    
                    <div className="flex flex-wrap gap-2">
                       <button 
                         onClick={() => handleGenerate(undefined, letter)}
                         disabled={generating}
                         className="flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-950 hover:bg-slate-800 text-slate-300 text-sm font-medium transition-colors border border-slate-800 hover:border-slate-700 disabled:opacity-50"
                       >
                         {generating ? <div className="h-4 w-4 rounded-full border-2 border-slate-500 border-t-white animate-spin" /> : <RefreshCcw className="h-4 w-4" />}
                         Regenerate
                       </button>
                       <button 
                         onClick={() => handleCopy(letter.id, letter.generatedText)}
                         className="flex items-center gap-2 px-4 py-2 rounded-lg bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 text-sm font-medium transition-colors border border-indigo-500/20 hover:border-indigo-500/30"
                       >
                         {copiedId === letter.id ? <CheckCircle className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                         {copiedId === letter.id ? "Copied!" : "Copy"}
                       </button>
                       <button 
                         onClick={() => handleDownloadPDF(letter)}
                         className="flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-sm font-medium transition-colors border border-slate-700 hover:border-slate-600"
                       >
                         <Download className="h-4 w-4" /> Export PDF
                       </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
