import React, { useState } from "react";
import { PenTool, CheckCircle, Copy, Loader2, Sparkles, RefreshCcw, Download } from "lucide-react";
import jsPDF from "jspdf";

export default function Rewrite({ token }: { token: string }) {
  const [form, setForm] = useState({
    type: "experience",
    text: "",
  });
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState("");
  const [copied, setCopied] = useState(false);

  const handleRewrite = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.text.trim()) {
      setError("Please enter the text you want to improve.");
      return;
    }
    
    setLoading(true);
    setError("");
    setResult("");
    setCopied(false);

    try {
      const res = await fetch("/api/cvs/rewrite", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${token}`
        },
        body: JSON.stringify(form)
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      
      setResult(data.result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (result) {
      navigator.clipboard.writeText(result);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadPDF = () => {
    if (!result) return;
    const doc = new jsPDF();
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const textAreaWidth = pageWidth - margin * 2;

    // Header styling
    doc.setFillColor(30, 41, 59); // slate-800
    doc.rect(0, 0, pageWidth, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("Improved CV Section", margin, 25);
    
    // Sub-header details
    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(`Type: ${form.type === 'experience' ? 'Experience / Job Description' : form.type === 'summary' ? 'Professional Summary' : form.type === 'skills' ? 'Skills & Expertise' : 'Custom'}`, margin, 55);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, 63);
    
    // Line separator
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(margin, 70, pageWidth - margin, 70);

    // Letter Content
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    const splitText = doc.splitTextToSize(String(result || ""), textAreaWidth);
    let currentY = 82;
    
    for (let i = 0; i < splitText.length; i++) {
      if (currentY > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        currentY = margin;
      }
      doc.text(splitText[i], margin, currentY);
      currentY += 6;
    }
    
    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Generated by AI CV Coach • ${new Date().getFullYear()}`, margin, pageHeight - 15);

    doc.save(`Improved_CV_${form.type}.pdf`);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div>
        <h1 className="font-display text-4xl font-bold text-white tracking-tight">AI CV Rewriter</h1>
        <p className="text-slate-400 mt-1">Enhance your resume sections with professional, ATS-optimized wording.</p>
      </div>

      {error && (
        <div className="bg-rose-500/10 border border-rose-500/20 text-rose-400 p-4 rounded-xl">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-stretch">
        <div className="space-y-6 flex flex-col h-full">
          <form onSubmit={handleRewrite} className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 backdrop-blur-sm space-y-4 flex flex-col h-full flex-grow">
            <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-indigo-400" /> Original Content
            </h3>
            
            <div>
              <label className="block text-xs text-slate-400 uppercase font-semibold tracking-wider mb-2">Content Type</label>
              <select 
                value={form.type}
                onChange={e => setForm({...form, type: e.target.value})}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg py-3 px-4 text-white focus:outline-none focus:border-indigo-500"
              >
                <option value="experience">Experience / Job Description</option>
                <option value="summary">Professional Summary</option>
                <option value="skills">Skills & Expertise</option>
                <option value="other">Other</option>
              </select>
            </div>

            <div className="flex-grow flex flex-col h-full min-h-[250px]">
              <label className="block text-xs text-slate-400 uppercase font-semibold tracking-wider mb-2 mt-4">Your Text</label>
              <textarea 
                required
                value={form.text}
                onChange={e => setForm({...form, text: e.target.value})}
                className="w-full h-full min-h-[200px] flex-grow bg-slate-950 border border-slate-800 rounded-lg py-3 px-4 text-white focus:outline-none focus:border-indigo-500 resize-none custom-scrollbar"
                placeholder="Paste your original text here..."
              />
            </div>

            <button 
              type="submit"
              disabled={loading}
              className="w-full py-3 mt-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-lg hover:from-indigo-500 hover:to-purple-500 transition-all shadow-lg shadow-indigo-600/20 disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin" />
                  Rewriting with AI...
                </>
              ) : (
                <>
                  <RefreshCcw className="h-4 w-4" />
                  Improve Content
                </>
              )}
            </button>
          </form>
        </div>

        <div className="space-y-6 flex flex-col h-full">
          <div className="p-6 rounded-2xl bg-indigo-500/5 border border-indigo-500/20 backdrop-blur-sm space-y-4 flex flex-col h-full flex-grow relative">
            <h3 className="text-lg font-bold text-white mb-2 flex items-center justify-between">
              <span className="flex items-center gap-2"><PenTool className="h-5 w-5 text-indigo-400" /> Improved Version</span>
              
              {result && (
                <div className="flex flex-wrap gap-2">
                  <button 
                    onClick={handleCopy}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-sm font-medium transition-colors border border-slate-700 hover:border-slate-600"
                  >
                    {copied ? <CheckCircle className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
                    {copied ? "Copied!" : "Copy"}
                  </button>
                  <button 
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition-colors border border-indigo-500 hover:border-indigo-400 shadow-lg"
                  >
                    <Download className="h-4 w-4" /> Export PDF
                  </button>
                </div>
              )}
            </h3>

            <div className="flex-grow bg-slate-950/50 border border-slate-800/50 rounded-lg p-4 overflow-y-auto min-h-[250px] custom-scrollbar">
              {loading ? (
                <div className="h-full flex flex-col items-center justify-center text-slate-500 space-y-4">
                  <div className="relative">
                     <div className="absolute inset-0 rounded-full blur-xl bg-indigo-500/20 animate-pulse"></div>
                     <Sparkles className="h-8 w-8 text-indigo-400 animate-pulse relative z-10" />
                  </div>
                  <p className="text-sm font-medium">Applying executive polish...</p>
                </div>
              ) : result ? (
                <div className="text-slate-200 whitespace-pre-wrap leading-relaxed text-sm">
                  {result}
                </div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-slate-500 space-y-2">
                  <PenTool className="h-8 w-8 opacity-20 mb-2" />
                  <p className="text-sm">Your improved text will appear here.</p>
                  <p className="text-xs opacity-60">Ready to copy and paste back into your resume.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
